### ISSUE TITLE
Support resolving directories

### ISSUE THREAD

**Issue by Alloyed** [hishamhm/datafile#12]
An interesting consequence of the Unix everything-is-a-file philosophy is that directories are files, too:
```
> = io.open("/home")
file (0x1ed48a0)
> = io.open("/home", 'w')
nil	/home: Is a directory	21
```
The same does not apply to Windows, it turns out:
```
> = io.open("C:/Users")
nil	C:/Users: Permission denied	13
> = io.open("C:/Users", 'w')
nil	C:/Users: Permission denied	13
```
This means that searching for a directory using datafile.path() will work fine on a Unix system, but fail on Windows, and fail in way that is impossible to distinguish from a permissions error.
You can explicitly check for directories using luafilesystem, but that would introduce a dependency on external C code. Maybe define an ``open_with(opener, path, mode)`` function and let users provide their own directory-checker?

**Comment by hishamhm** [comment]
I just uploaded datafile 0.3, in which this issue should be fixed. Please take a look, thanks!
