### ISSUE TITLE
datafile as a shortcut doesn't seem to work

### ISSUE THREAD

**Issue by vadi2** [hishamhm/datafile#13]
```
> datafile = require("datafile")
> =datafile()
stdin:1: attempt to call global 'datafile' (a table value)
stack traceback:
	stdin:1: in main chunk
	[C]: ?
```

Using version 0.2-1.

**Comment by hishamhm** [comment]
Ah, thanks for reporting. This is actually a documentation bug, this feature was proposed but dropped, because having `datafile()` as function would not be clear if it meant `datafile.open()` or `datafile.path()`. I preferred to keep the API explicit. I will fix the documentation. Thank you!
