### ISSUE TITLE
Possible to remove openers?

### ISSUE THREAD

**Issue by deepakjois** [hishamhm/datafile#14]
In order to avoid any false positives, it would be nice to allow removing of openers from the list that is created by default. Maybe I am missing something, but from what I can see it is possible to add modules easily to datafile.openers, but not straightforward to remove a module by name.

**Comment by hishamhm** [comment]
> Maybe I am missing something, but from what I can see it is possible to add modules easily to datafile.openers, but not straightforward to remove a module by name.

It works just like `package.loaders` and other Lua configuration tables. If you want to remove an opener, loop through the `datafile.openers` table and `table.remove` the one you don't want there. But the default settings shouldn't produce false positives; let me know if you run into issues with them.
