### ISSUE TITLE
LuaRocks opener does not work when called with datafile.path(…)

### ISSUE THREAD

**Issue by deepakjois** [hishamhm/datafile#15]
This is because of the logic in the code at the end of the comment. `datafile.path` calls `datafile.open` which creates two entries in the stack for `datafile.lua`. The code below assumes wrongly that there can only be one entry ever, after which we can get the source file of the calling code. This assumption works for `datafile.open`, but does not work for `datafile.path`.

A robust fix would be to start a separate loop after the first time we encounter `datafile.lua`, until the last occurence of `datafile.lua`.

```lua
-- returns the stack level (for the caller) + sourcefile from where
-- 'datafile' module was called or nil + error
function util.stacklevel()
-- …snip…
   while info do
      info = debug.getinfo(level, "S")
      level = level + 1  -- inc before check because me need the match + 1
      if info and info.source:match("datafile.lua$") then -- FIXME faulty logic
         info = debug.getinfo(level, "S")
         break
      end
   end
-- …snip…
end
```

**Comment by hishamhm** [comment]
Thank you for the bug report!! I'm working on a fix right now.

**Comment by hishamhm** [comment]
I just uploaded datafile 0.3, in which this issue should be fixed. Please take a look, thanks!

**Comment by deepakjois** [comment]
Will do, but might take a while. Filing an issue in my project so that I remember Thank you.
