### ISSUE TITLE
File is not found on read-only file system

### ISSUE THREAD

**Issue by hanshuebner** [hishamhm/datafile#24]
If a file resides on a read-only file system, it is not found by the `find_file` function because it tries to rename the file, which fails with `EROFS` (https://github.com/hishamhm/datafile/blob/master/datafile.lua#L53).

I find the use of `os.rename` to probe for file existence to be a bit questionable, but if it is to be that way, error codes 1 (`EPERM`) and 30 (`EROFS`) should be handled like `EACCESS`.  Maybe it would be better to consider only `ENOENT` to be an indicator of non-existence or use open/close instead.

**Comment by Tieske** [comment]
are the error codes even platform independent?

**Comment by hishamhm** [comment]
> I find the use of os.rename to probe for file existence to be a bit questionable

So do I, but I have a faint memory that this was the most portable way to do it (`open` will create a file if it doesn't exist).

> are the error codes even platform independent?

Somewhat. I remember testing this on Windows and Linux back in the day, and the existing setup currently in the code works.

> error codes 1 (EPERM) and 30 (EROFS) should be handled like EACCESS

Doesn't `EPERM` mean that the file itself is not readable? Not sure. In any case, if changing that code to `if code == 13 or code == 30 then` fixes the current issue, I'd just rather take that for the moment.

**Comment by hanshuebner** [comment]
I would rather only take `ENOENT` as the indicator that the file does not exist.  After all, this is the `path` function, not the `can I access the file` function.  If the file exists but is not accessible, then the subsequent open will have a clear enough error message.

Regarding the portability, ChatGPT is of this opinion:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/108751/222241999-4c0b77b9-f4ea-47ed-831b-432524ffb612.png">

<img width="728" alt="image" src="https://user-images.githubusercontent.com/108751/222241809-3d021c4a-effe-462d-b8e1-8415f1de85b1.png">

It lied to me before, though.

**Comment by hishamhm** [comment]
Come on, you're not seriously using ChatGPT as a source, are you? :laughing:

**Comment by hanshuebner** [comment]
> Come on, you're not seriously using ChatGPT as a source, are you? 😆

Not seriously, but I like to play with it.  Sometimes it is really grotesque to watch it make up things, but in this case, it seems to be accurate.

**Comment by hishamhm** [comment]
Given that...

> It lied to me before, though.

...and that this tool is _designed_ to produce plausible-sounding text, and _not_ true information, "seeming to be accurate" is definitely not enough. To know for sure, we'd have to actually check the POSIX specs, and if we need to double-check by hand everything it outputs, then that entirely defeats the purpose of using it as an information source.

I can see it being very useful in the hands of those wanting to produce truthy-sounding misinformation (unsurprising, given the politics of the people funding it), but as for me, I'd steer clear from it for any serious work where any accuracy is wanted.

But back to the subject at hand, I'm less concerned about what POSIX says and more about what works in the wild, including Windows... whose reading of POSIX is often peculiar! 

And honestly, I don't feel like going back and testing the change back on every OS I can get my hands on... I don't have VMs for a bunch of random OSes like I had in the past when I last tested this, much less ones configured with readonly filesystems, etc. — so I'd much rather go with the smallest possible change which I know won't break anything on other systems where things are currently working.

**Comment by hanshuebner** [comment]
> I'd much rather go with the smallest possible change which I know won't break anything on other systems where things are currently working.

An additional check for EROFS (30) will suffice to fix the particular bug that made me look into this.

**Comment by hishamhm** [comment]
@hanshuebner just pushed release 0.8 with the change!

**Comment by hanshuebner** [comment]
Thanks for the quick turnaround!

**Comment by hanshuebner** [comment]
To close up the issue, ChatGPT lied again as it claims that [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_03) specifies the possible `errno` values when it does not.  It even says explicitly that the actual values are unspecified.
```
The following macro names identify the possible error numbers, in the context of the functions specifically defined in this volume of POSIX.1-2017; these general descriptions are more precisely defined in the ERRORS sections of the functions that return them. Only these macro names should be used in programs, since the actual value of the error number is unspecified. All values listed in this section shall be unique, except as noted below. The values for all these macros shall be found in the [<errno.h>](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html) header defined in the Base Definitions volume of POSIX.1-2017. The actual values are unspecified by this volume of POSIX.1-2017.
```
