### ISSUE TITLE
is traversing all the way up wise?

### ISSUE THREAD

**Issue by Tieske** [hishamhm/datafile#8]
````
Program starting as '"C:\Program Files (x86)\ZeroBraneStudio\bin\lua.exe" -e "io.stdout:setvbuf('no')" "C:\Users\Thijs\Dropbox\Lua projects\test.lua"'.
Program 'lua.exe' started in 'C:\Users\Thijs\Dropbox\Lua projects' (pid: 5880).
nil	file 'myapp/config.file' not found:
	could not recognize @C:/Users/Thijs/Dropbox/Lua projects/test.lua as a LuaRocks module
	no file 'C:/Users/Thijs/Dropbox/Lua projects/myapp/config.file'
	no file 'C:/Users/Thijs/Dropbox/myapp/config.file'
	no file 'C:/Users/Thijs/myapp/config.file'
	no file 'C:/Users/myapp/config.file'
	no file 'C:/myapp/config.file'
	no file 'C:\Users\Thijs\AppData\Roaming\myapp/config.file'
	no file 'C:\ProgramData\myapp/config.file'
	no file 'C:\Users\Thijs\myapp/config.file'
	no file 'C:\Users\Public\myapp/config.file'
	myapp/config.file: No such file or directory	11
Program completed in 0.13 seconds (pid: 5880).
````

See the above. After LuaRocks lookup fails, it starts from the caller script directory and traverses all the way up. I don't like this. If one uses a common name, eg. `settings.cfg` then the risk of hitting some match along the way is getting bigger. If something is located relative to a script, then the script knows where and can add `/../../` or whatever to locate it properly

or am I being overly cautious?

**Comment by hishamhm** [comment]
I see what you mean. The idea of datafile is to not have things like `/../../` in the code, since tree layouts vary greatly among systems. But indeed going all the way up seems too much... I need to take a look at how people are using datafile out there before I make an incompatible change, though.

**Comment by Tieske** [comment]
I think the main point I'm trying to make is that traversing up in unpredictable. A programmer has no idea where a user might install a program. So traversing up is unpredictable and that should not happen.

It has 42 downloads (the rock), funny number :smile:

**Comment by hishamhm** [comment]
Done! I will move that Unix part out of the `caller` opener now.
